### ISSUE TITLE
Get into Debian repositories

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1050]

**Comment by ghorn** [comment]
Casadi can be built with the debian build system lintian clean, and unit tests pass. I'm closing `wontfix` because we decided that an Ubuntu PPA would be better so that we can control updates. Not sure what the right solution for Debian is; if it's possible to bar the casadi package from getting synced to ubuntu maybe we should just upload to Debian.

**Comment by AustinSchuh** [comment]
It would be quite nice to be able to install Casadi via apt, at the very least, to make it easy to get started on a project using it on Debian proper.  The current rate of releases and change is also a lot lower now than when this was last looked at, so the update delay is likely a lot less of a concern.
