### ISSUE TITLE
Formulating QPs using NLP syntax

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1335]
I think it should be possible to formulate QPs using NLP syntax:
```python
H = MX.sym('H',n,n)
A = MX.sym('A',n,m)
c = MX.sym('c', n)
x = MX.sym('x',n)
solver = Solver('qpoases',
    x=x, p=horzcat([H, A, c]),
    f=quad_form(H,x) + inner_prod(c,x), g=mul(A.T,x))
```
where `Solver(name, x=xx, p=pp, f=ff, g=gg)` is a shorthand for:
```python
if x.__class__==MX:
   solver = NlpSolver(name,MXFunction(nlp_in(x=xx, p=pp), nlp_out(f=ff, g=gg))
else:
   solver = NlpSolver(name,SXFunction(nlp_in(x=xx, p=pp), nlp_out(f=ff, g=gg))
```

The NLP solver class should be able to automatically reformulate such NLPs as QPs. Also, by using the shorthand (which could be considered a separate issue), the user would not need to know about IO schemes.

**Comment by csavorgn** [comment]
I like this idea!
I think that this could be made slightly more ambitious trying to find a common formulation for all solvers interfaced with Casadi. Therefore, also quadratic constraints, semidefinite constraints, etc. should be considered.
Finding a common formulation could give also the chance to add a standard way to indicate which variables are integer so that one could use the mixed integer capabilities of cplex and knitro or other solvers not currently interfaced like Gurobi. Casadi is clearly not a software aimed at solving MILPs or other mixed integer problem, but the extra feature would be nice (especially for MINLP).
One more thing to consider is the following: maybe the possibility of passing the matrices defining a linear/quadratic cost and constraints should be given. This feature could be useful when embedding a solver into another solver, e.g. for writing a SCP solver.
One question for @jgillis and @ghorn: SNOPT treats linear constraints in a special way. How do you currently deal with this?

**Comment by jaeandersson** [comment]
SDPs can in principle also be written as NLPs:
```python
X = MX.sym('x',n,n)
C = ...
solver = Solver('qpoases',
    x=X, p=horzcat([X, C]),
    f=inner_prod(X,C), g=norm_2(X))
```
Need to add better support for handling symmetric matrices first though.

**Comment by csavorgn** [comment]
Another option for dealing with SDPs is using the following
inner_prod(X, C) = trace(X^T C) = vec(X)^T vec(C)
where vec(X) is the operator which returns a vector by concatenating the columns of X.
Now instead of dealing with matrix optimization variables you would just work with vectors.
This "trick" is used also in the matlab interface of sedumi or other SDP solvers.
I think that it could be better working with vectors because usually people don't have their problems in standard form (with matrices) and they have to convert them. Therefore, for the joy of users, it could be done automatically.

**Comment by jaeandersson** [comment]
The definition of `inner_prod(X,Y)` in CasADi is already defined as `tr(X.T, Y)`. And `vec(X)` already stacks the columns... There is nothing wrong in using matrix variables in CasADi, it was written for that. Indeed, since we are talking about a symmetric matrix the natural decision variable is actually a sparse (upper triangular) decision variable.

**Comment by jaeandersson** [comment]
Formulating QPs using NLP syntax is covered by #1590. For other issues discussed above, I suggest a separate issue if action needs to be taken.
