### ISSUE TITLE
Bug casting from Numpy array to SX

### ISSUE THREAD

**Issue by mrisbeck** [casadi/casadi#1401]
As of version 2.3rc1, casting from a Numpy array of SX to SX doesn't work properly. The code

    import casadi
    import numpy as np
    x = casadi.SX.sym("x",3)
    print "x =", repr(x), "\n"
    print "array(x) =", repr(np.array(x)), "\n"
    print "SX(array(x)) =", repr(casadi.SX(np.array(x))), "\n"

gives

    x = SX([x_0, x_1, x_2]) 
    
    array(x) = array([[SX(x_0)],
           [SX(x_1)],
           [SX(x_2)]], dtype=object) 
   
    SX(array(x)) = SX([x_2, 0, 0]) 

i.e., the last element ends up in the first position and all other elements are zero. In older versions, the last line gives

    SX(array(x)) =  SX([x_0, x_1, x_2])

as expected.

**Comment by jgillis** [comment]
Thank you for reporting this critical error. A release 2.3.0-rc3 is brewing with a fix.

**Comment by jaeandersson** [comment]
Why is `SX(array(SX))` supported at all? When does it make sense?

**Comment by jgillis** [comment]
It makes sense for numpy-oriented codes; given enough similarity; they may work with casadi symbolics out of the box.

**Comment by jaeandersson** [comment]
In general, I think it is dangerous to support features that "may work".

**Comment by ShaoshuSu** [comment]
Hi may I ask does Casadi still support numpy right now?
I meet a problem like this:

_---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/anaconda3/envs/shaoshu/lib/python3.8/site-packages/casadi/casadi.py:9209, in SX.__array__(self, *args, **kwargs)
   9208 try:
-> 9209   return self.full()
   9210 except:

File ~/anaconda3/envs/shaoshu/lib/python3.8/site-packages/casadi/casadi.py:7977, in SX.<lambda>(self, name)
   7976     __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
-> 7977 __getattr__ = lambda self, name: _swig_getattr(self, SX, name)
   7978 __repr__ = _swig_repr

File ~/anaconda3/envs/shaoshu/lib/python3.8/site-packages/casadi/casadi.py:83, in _swig_getattr(self, class_type, name)
     82     return method(self)
---> 83 raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))

AttributeError: 'SX' object has no attribute 'full'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
/home/msc/shaoshu/test_casadi.ipynb Cell 2 in <cell line: 2>()
      [1](vscode-notebook-cell:/home/msc/shaoshu/test_casadi.ipynb#W3sZmlsZQ%3D%3D?line=0) x = SX.sym("x",3)
----> [2](vscode-notebook-cell:/home/msc/shaoshu/test_casadi.ipynb#W3sZmlsZQ%3D%3D?line=1) np.array(x)

File ~/anaconda3/envs/shaoshu/lib/python3.8/site-packages/casadi/casadi.py:9211, in SX.__array__(self, *args, **kwargs)
   9209   return self.full()
   9210 except:
-> 9211   raise Exception("Implicit conversion of symbolic CasADi type to numeric matrix not supported.\n"
   9212              + "This may occur when you pass a CasADi object to a numpy function.\n"
   9213              + "Use an equivalent CasADi function instead of that numpy function.")

Exception: Implicit conversion of symbolic CasADi type to numeric matrix not supported.
This may occur when you pass a CasADi object to a numpy function.
Use an equivalent CasADi function instead of that numpy function._

**Comment by Mrzhang-hub** [comment]
> Hi may I ask does Casadi still support numpy right now? I meet a problem like this:
> 
> `--------------------------------------------------------------------------- AttributeError Traceback (most recent call last) File ~/anaconda3/envs/shaoshu/lib/python3.8/site-packages/casadi/casadi.py:9209, in SX.**array**(self, *args, **kwargs) 9208 try: -> 9209 return self.full() 9210 except:
> 
> File ~/anaconda3/envs/shaoshu/lib/python3.8/site-packages/casadi/casadi.py:7977, in SX.(self, name) 7976 **swig_getmethods**.update(getattr(_s, '**swig_getmethods**', {})) -> 7977 **getattr** = lambda self, name: _swig_getattr(self, SX, name) 7978 **repr** = _swig_repr
> 
> File ~/anaconda3/envs/shaoshu/lib/python3.8/site-packages/casadi/casadi.py:83, in _swig_getattr(self, class_type, name) 82 return method(self) ---> 83 raise AttributeError("'%s' object has no attribute '%s'" % (class_type.**name**, name))
> 
> AttributeError: 'SX' object has no attribute 'full'
> 
> During handling of the above exception, another exception occurred:
> 
> Exception Traceback (most recent call last) /home/msc/shaoshu/test_casadi.ipynb Cell 2 in <cell line: 2>() 1 x = SX.sym("x",3) ----> 2 np.array(x)
> 
> File ~/anaconda3/envs/shaoshu/lib/python3.8/site-packages/casadi/casadi.py:9211, in SX.**array**(self, *args, **kwargs) 9209 return self.full() 9210 except: -> 9211 raise Exception("Implicit conversion of symbolic CasADi type to numeric matrix not supported.\n" 9212 + "This may occur when you pass a CasADi object to a numpy function.\n" 9213 + "Use an equivalent CasADi function instead of that numpy function.")
> 
> Exception: Implicit conversion of symbolic CasADi type to numeric matrix not supported. This may occur when you pass a CasADi object to a numpy function. Use an equivalent CasADi function instead of that numpy function.`

I meet the same problem. Have you solved it?

**Comment by ha7ilm** [comment]
In this case you are trying to convert a *symbolic* expression to numpy, which does not make sense.
Remove all the symbols first (i.e. substitute, or evaluate a `casadi.Function`).

In MATLAB, it looks like this for example: `full(evalf(substitute(my_casadi_symbolic_expression, my_casadi_symbol, numeric_values_to_plug_in)))`. 

Then use these steps:

https://github.com/casadi/casadi/wiki/FAQ:-How-to-transform-a-Casadi-matrix-to-a-Numpy-array
