### ISSUE TITLE
User data in external function interface

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1417]
Codegen doesn't need it but black box functions may.

**Comment by jaeandersson** [comment]
To accommodate user data, I'd add a `free` entry point and change the `init` entry point to return a pointer instead of an error flag:
```c
void* f_init(int *f_type, int *n_in, int *n_out, int *sz_arg, int* sz_res);
int f_free(void *mem);
```

The error handling would then be checking if the returned memory is non-null. For functions without memory (i.e. all classes currently supporting codegen), one could simply return one of the arguments cast to void*:
```c
void* f_init(int *f_type, int *n_in, int *n_out, int *sz_arg, int* sz_res) {
  return f_type;
}
int f_free(void *mem) {
 /* nothing to free */
}
```
If the return value equals, `f_type`, then the user could in principle assign the memory to null explicitly:
```c
int f_type, n_in, n_out, sz_arg, sz_res;
void *mem = f_init(&f_type, &n_in, &n_out, &sz_arg, &sz_res);
casadi_assert(mem!=0);
if (mem==&f_type) mem=0;
```

**Comment by jaeandersson** [comment]
@toivoh Please have a look at the above.

**Comment by jaeandersson** [comment]
Slight modification, I'll change the init function to:
```c
void* f_init(void *data, int *f_type, int *n_in, int *n_out, int *sz_arg, int* sz_res);
```
That will allow passing a user data structure with problem information. Unlike `mem`, this memory is shared among all objects and the user must ensure that the access is thread-safe. For memory-less functions, `data` would also be the return value of `f_init`.

An example of `data` would be data for a lookup-table.

**Comment by toivoh** [comment]
I will try to describe my use case which looks a bit different, and we'll see what we can come up with. Also, I think we need to widen the discussion to how `ExternalFunction` would use the update interface, and how the user would use `ExternalFunction`.

As it is now, a CasADi `Function` is called with a number of real matrix valued arguments. Ideally, I would want an `ExternalFunction` to be able to take one or several void pointers as additional arguments when it is called. But since the only datatype that CasADi works with so far is real matrices, I understand that this would probably require a major redesign.

Alternatively, it would be useful to be able to specify a void pointer for user data when creating an `ExternalFunction`.
* The user data would be sent to `f` and `f_work`, and could be sent to `f_sparsity` as well (though we don't need that for our application). It could also be sent to `f_init`.
* The same external function would then be instantiated multiple times with different user data to be used for different call sites.
    * It could then be useful with an `ExternalFunction` constructor that would use the same external functions as another `ExternalFunction`, but change the user data, if it would be costly to look up the interface functions `f_init` etc many times.

So it might be that the best route includes to add a user data pointer that is sent to `f_init`, `f_work`, `f_sparsity`, and `f`, but from my perspective that should just be an opaque pointer provided by the user when constructing the `ExternalFunction`. It wouldn't make sense from my perspective to make `f_init` into a constructor for the user data; the constructors I would call would have different signatures. It still seems like a good idea to have `f_free` though, to signal when CasADi doesn't need the user data anymore.

**Comment by toivoh** [comment]
Also, I don't see why the user data shouldn't be allowed to be null. That seems like it would be the reasonable value to use if the external function doesn't need any user data.

**Comment by toivoh** [comment]
Another thing to consider is how the user data is handled when the dll with external functions includes derivative functions. But I guess that you would just pass the same user data pointer as to the original function. That also means that there could be multiple calls to `f_free` for the same user data; if so I guess they should be matched to an equal number of `f_init` calls for that user data.

**Comment by jaeandersson** [comment]
The new codegen design allows this for all practical purposes. While no "void*" can be passed to CasADi, the interface code can maintain a set of void pointers in a struct and the indices to this struct is what gets passed back and forth to the external function interface.
