### ISSUE TITLE
"mtimes" instead of "mul" for matrix multiplication

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1499]
The "mul" symbol for matrix multiplication is non-standard. We could consider using "mtimes" instead.

**Comment by jgillis** [comment]
Is this referring to Python? `mul` was deliberately chosen to be non-standard to avoid conflicts.
`mul` is already long to type...

**Comment by jaeandersson** [comment]
It was chosen not to be "dot" or "prod" to avoid conflict with the numpy equivalents. "mtimes" in MATLAB is exactly the same as "mul" on the other hand.

**Comment by jaeandersson** [comment]
Note that Python 3.5 has a matrix multiplication operator:
```
A @ B
```
http://legacy.python.org/dev/peps/pep-0465/

**Comment by jgillis** [comment]
veto on Python.

**Comment by jgillis** [comment]
veto did not work; it's long there..

**Comment by drewm1980** [comment]
Hi guys, what was the final result? what is matrix multiplication in the python API? The python API docstrings only contain function signatures.

**Comment by drewm1980** [comment]
looks like mtimes and A@B both work... wasn't sure because the name of the returned 'mac' object didn't mean anything to me.

**Comment by jgillis** [comment]
Hi Andrew!

in python 3, use @. In older python mtimes.

On Jan 4, 2018 5:34 PM, "Andrew Wagner" <notifications@github.com> wrote:

Hi guys, what was the final result? what is matrix multiplication in the
python API? The python API docstrings only contain function signatures.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/casadi/casadi/issues/1499#issuecomment-355330265>, or mute
the thread
