### ISSUE TITLE
MA27 solver in MAC-OS binary version

### ISSUE THREAD

**Issue by kschischo** [casadi/casadi#1766]
Thank you for developing casadi. I think its a great project. I am trying to use casadi for a data assimilation problem in systems biology, see http://www.nature.com/articles/srep20772.

I installed the binaries and tried some of the examples. While vdp_multiple_shooting.py worked fine, 
I had problems with other examples. It seems that MA27 is not avaliable. 

runfile('/Users/kschisch/Myconfig/python/casadi-example_pack-v3/python/vdp_collocation2.py', wdir='/Users/kschisch/Myconfig/python/casadi-example_pack-v3/python')
Reloaded modules: casadi.casadi, _casadi, casadi._casadi, casadi
Exception of type: OPTION_INVALID in file "../../../../Ipopt/src/Algorithm/IpAlgBuilder.cpp" at line 321:
 Exception message: Selected linear solver MA27 not available.
Tried to obtain MA27 from shared library "libhsl.dylib", but the following error occured:
dlopen(libhsl.dylib, 2): image not found

Any advice? What is MA27 anyway? Is it needed for IPOPT?

**Comment by jgillis** [comment]
Hi!

Inside the open-source interior-point NLP solver IPOPT,
you need to repeatedly factorise a large sparse system.

IPOPT offers quite a few interfaces to linear solvers, among which 'mumps', an open-source solver that comes shipped with it. You can specify 'linear_solver' : 'mumps' as option or just remove the option alltogether since it is the default.

MA27 is one of the few solvers of the proprietary HSL library ( http://www.hsl.rl.ac.uk/ipopt/ ).
The HSL solvers usually give superior results for optimal control; sometimes it makes the difference between convergence or no convergence.

You can find installation instructions on https://github.com/casadi/casadi/wiki/Obtaining-HSL

**Comment by kschischo** [comment]
Hi 

thank you very much. Disabling MA27 made it work. 
I am using anaconda, because I didn’t want to mess up my mac python installation. I wish I would never have got a Mac.
Linux is much better for this. 

I will anyway try to get the HSL solvers run with ipopt under anaconda. Maybe, this will be helpful for other users as well.
Will possibly take some time and lots of coffee.

Best wishes,

Maik


> On 19 Apr 2016, at 11:07, jgillis <notifications@github.com> wrote:
> 
> Hi!
> 
> Inside the open-source interior-point NLP solver IPOPT,
> you need to repeatedly factorise a large sparse system.
> 
> IPOPT offers quite a few interfaces to linear solvers, among which 'mumps', an open-source solver that comes shipped with it. You can specify 'linear_solver' : 'mumps' as option or just remove the option alltogether since it is the default.
> 
> MA27 is one of the few solvers of the proprietary HSL library ( http://www.hsl.rl.ac.uk/ipopt/ <http://www.hsl.rl.ac.uk/ipopt/> ).
> The HSL solvers usually give superior results for optimal control; sometimes it makes the difference between convergence or no convergence.
> 
> You can find installation instructions on https://github.com/casadi/casadi/wiki/Obtaining-HSL <https://github.com/casadi/casadi/wiki/Obtaining-HSL>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/casadi/casadi/issues/1766#issuecomment-211815285>

######################
Dr. Maik Kschischo
Frongasse 6
53424 Remagen

maik.kschischo@yahoo.de
######################
