### ISSUE TITLE
Control flow supported, like for loops and if statements?

### ISSUE THREAD

**Issue by alexbw** [casadi/casadi#1833]
Does casadi support differentiating through control flow?

**Comment by jaeandersson** [comment]
CasADi's approach to flow control is inspired by functional programming languages like Haskell, and you have to reformulate for loops or if statements to be to represent them as CasADi expressions. For example, you'd use a "map" (or the related "mapaccum", "mapsum") instead of a for loop and an "if_else" or "conditional" operation instead if an if statement. If you do this, differentiation is supported, in the "almost everywhere" sense. Flow control support is still work in progress, so don't be surprised if you run into a bug.
