### ISSUE TITLE
Bonmin options not recognized

### ISSUE THREAD

**Issue by edmundus** [casadi/casadi#1926]
While passing options to IPOPT is possible
                opts = {"ipopt.print_level": 0,}
the same has no effect on BONMIN and no error is given if for example the following is passed:
                opts = {"bonmin.bb_log_interval": 0,
                            "bonmin.asdf":0,}

**Comment by jgillis** [comment]
Right, at the moment you may only set bonmin's options via an `bonmin.opt` file.

**Comment by edmundus** [comment]
is there a way to set the path to the `bonmin.opt` in the casadi 3.1 RC ?

**Comment by jgillis** [comment]
No, the current directory is always searched..

Op 2-jan.-2017 17:18 schreef "edmundus" <notifications@github.com>:

is there a way to set the path to the bonmin.opt in the casadi 3.1 RC ?

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/casadi/casadi/issues/1926#issuecomment-269992190>, or mute
the thread
