### ISSUE TITLE
Build fails with two examples

### ISSUE THREAD

**Issue by stephane-caron** [casadi/casadi#1956]
Hi there,

Building a fresh pull from master today, the build fails when compiling the example ``parametric_sensitivities.cpp``:

```
~/casadi/docs/examples/cplusplus/parametric_sensitivities.cpp: In function ‘int main()’:
~/casadi/docs/examples/cplusplus/parametric_sensitivities.cpp:133:27: error: ‘class casadi::Function’ has no member named ‘getStat’
   var_numeric_md = solver.getStat("var_numeric_md");
```

Second, the example ``reduced_hessian.cpp`` also seems to fail:

```
~/casadi/docs/examples/cplusplus/reduced_hessian.cpp: In function ‘int main()’:
~/casadi/docs/examples/cplusplus/reduced_hessian.cpp:103:26: error: ‘class casadi::Function’ has no member named ‘getReducedHessian’
     DM red_hess = solver.getReducedHessian();
```

Once these two are commented out the rest of the build terminates.

Best,

**Comment by jaeandersson** [comment]
Yeah, these two examples use sIPOPT, support for which has been dropped. The examples (and hence your error) have already been removed in the develop branch. If it's a blocking issue (I guess it's not), we could make a minor release, otherwise the fix will propagate to master when we make the next release.
