### ISSUE TITLE
'eval_sx' not defined for N6casadi6SwitchE

### ISSUE THREAD

**Issue by mahaarbo** [casadi/casadi#1967]
Hi,

I've implemented some cubic splines using the if_else function. It runs fine as long as I define the variables using MX, but it seems it doesn't support SX. 
It might have been a bit too ambitious to trace a complex curve with 45 if_else statements, as the hessian evaluations take quite some time.

**Comment by jaeandersson** [comment]
Your error message just means that the the automatic MX-to-SX is not defined for the type of short-circuiting switches defined in MX. I think that this has already been changed in latest development version, but using it could lead to a combinatorial expansion. My recommendation would be for you to do `if_else(c, x, y, False)` instead of `if_else(c, x, y)` and see what happens. That makes much more sense, especially if you later do the MX-to-SX expansion afterwards. Then you won't need to update your CasADi version either.

**Comment by jgillis** [comment]
Fwiw, there is now 'bspline' in development branch, which performs efficient evaluation of bsplines.
This function is not expandable to SX however.
