### ISSUE TITLE
Bump octave version to 4.2.1

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2002]
Blocked by missing information.

As of octave version 4.2, the structure of the [octave binaries](https://ftp.gnu.org/gnu/octave/windows/) changed for windows:  there are now 2 flavours, using 32 and 64 prefixes.
It's not clear to me how these new downloads map to the 3 octave-crossbuild configurations documented at http://wiki.octave.org/Continuous_Build: `w32-on-debian` 	, `w64-32-on-debian` 	, `w64-64-on-debian`

Does the 32 prefixed download correspond to `w32-on-debian` or to `w64-32-on-debian`?

**Comment by jweaton** [comment]
The configuration for the buildbot builds is as follows:

  w32:  32-bit Windows, so 32-bit pointers and limited to 32-bit indexing.  You can only allocate up to about 4GB total memory because of the limit imposed by using 32-bit pointers.  This is distributed as the w32 binary on ftp.gnu.org.

  w64-32:  64-bit Windows, so 64-bit pointers, allowing larger memory allocation, but limited to 32-bit indexing in Octave.  This allows arrays up to about 2^31 elements, so for a double precision array, that requires about 16GB of memory.  This is distributed as the w64 binary on ftp.gnu.org.

  w64-64:  64-bit Windows and 64-bit indexing.  We're not distributing this one as a binary release.

**Comment by jgillis** [comment]
Bump finished
