### ISSUE TITLE
Single argument min and max

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#2043]
The single-argument versions of min and max (that returns the largest or smallest element in the matrix appear naturally in user codes.

**Comment by jaeandersson** [comment]
An MX node would greatly benefit from symbolic indexing. The derivative rules are as follows:
For y = mmin(x)
Forward mode:
y_hat = x_hat[find(x==y)]
Reverse mode:
x_bar[find(x==y)] += y_bar

**Comment by jaeandersson** [comment]
Cf. #728

**Comment by deego** [comment]
Many thanks for max.


It would be great to allow per-dimension min/max for matrices. For clarify, it could be named reduce_min a la TF, or it could use the generalized octave/matlab syntax as below:



In TF for example, this facility is called reduce_max and allows a dimension as an argument.

In MATLAB/OCTAVE, the syntax is:

min(x,[], dim).

That is interpreted as a request to output a vector containing the min of x along dimension dim.

In fact, min(x) is interepreted to mean min(x,[], 1)  for matrices, (and if x is a vector, the dimension defaults to dwim.)

Of course, min(x,y) continues to take elementwise min of x and y
---

At the present moment, in casadi, min(x) returns a single item containing the min of the whole matrix. In octave/matlab, the equivalent would be min(min(x)), or min(x(:)).
----

Finally, y= max(x) is now implemented in casadi, but the moment I do something like z = x*x(1), 
I cannot take the gradient of z any more or use that in functions. [where x is a MX]. That's because gradient is not defined. Defining a gradient of a max() would be trivial: The gradient is 1 for the matched index, and 0 otherwise.  [very similar to how the gradient of max(x,y) works.]

**Comment by deego** [comment]
(oops, I didn't mean to shout or bold anything. I will slowly get the hang of this formatting.)

**Comment by jaeandersson** [comment]
The unexpected behavior of single-argument min/max for matrices is similar to the issue #2099

**Comment by jgillis** [comment]
Why is it that the differentiation rule of fmin is taken `d[0]=x<=y; d[1]=!d[0];` as opposed to `d[0]=x<=y; d[1]=x>=y;`?
In the latter case, the AD rule for mmin would generalize to

For y = mmin(x)
Forward mode:
y_hat = dot(x_hat,x==y)
Reverse mode:
x_bar += y_bar*(x==y)

**Comment by jaeandersson** [comment]
> Why is it that the differentiation rule of fmin is taken d[0]=x<=y; d[1]=!d[0]; as opposed to d[0]=x<=y; d[1]=x>=y;?

I think this choice was made to make sure that the derivative rule was correct even x and y are equal.
You'd expect that fmax(x, x) would behave like x. With your suggestion, the derivative would be 2, not one, which doesn't really make sense.

Arguably, you'd want to make it symmetric however. So, maybe
a = x<=y
b = y<=x
c = a+b
d[0]= a/c
b[0]= b/c

Your suggested rule suffers from the same potential pitfall. So, maybe

a = x==y
Forward mode:
y_hat = sum(a)*dot(x_hat,a)
Reverse mode:
x_bar += (y_bar/sum(a))*a

**Comment by jaeandersson** [comment]
You want to make sure that the simplification fmin(x,x)->x won't change the derivative rule. Otherwise you'll get some nasty potential bugs

**Comment by nicklarson6** [comment]
Did this get fixed? I am trying to use mmax and still getting ''ad_reverse' not defined for class N6casadi4MMinE'.

Thanks

**Comment by jgillis** [comment]
The practical implementation of non-symmetric ad rules for `mmin` gets really messy..

Something like
```
    MX i = find(vec(shared_from_this<MX>())==vec(dep(0)));
    MX r = fmod(i, dep(0).size1());
    MX c = (i-r)/dep(0).size1();
    for (casadi_int d=0; d<fsens.size(); ++d) {
      fsens[d][0] = fseed[d][0](r,c);
    }
```
but parametric `MX::get` is only implemented for dense matrices, and not at all for `MX::set`.
Working with `MX::get_nz/set_nz` is supported, but then it gets messy to convert `find` output (which gives a row index)
