### ISSUE TITLE
Opti.solve should not throw exception when solver fails

### ISSUE THREAD

**Issue by nxtruong** [casadi/casadi#2138]
In version 3.3 for Matlab, when I call
`sol = opti.solve()`
and the solver fails (for example: Infeasible), it throws an exception:

> Error using casadi.Opti/solve (line 233)
> Error in Opti::solve [OptiNode] at .../casadi/core/optistack.cpp:158:
> .../casadi/core/optistack_internal.cpp:909: Assertion "success" failed:
> Solver failed. You may use opti.debug.value to investigate the latest values of variables.
> return_status is 'Infeasible_Problem_Detected'

The solve() method should fail gracefully. It should not throw an exception. Rather, it should return the status of the solver, either in a separate output or in `stats.return_status`.

**Comment by jgillis** [comment]
Hi! This is by design in fact. The idea is that you cannot accidentilly end up using an non-converged solution.
One must use try catch, and opti.debug, providing a strong visual cue that you are doing something hacky (ie ignoring the fact that the solver failed and proceesing anyway).
It is intended that more diagnostics information is shown at failure, eg showing which constraints are infeasible.

**Comment by nxtruong** [comment]
Make sense. Will Opti.solve() throw an exception in the cases of max number of iterations reached and max time reached (any case except "optimal solution found")? By the way, this behavior should be mentioned in the manual. I didn't find it in the manual, and was caught surprised when it occurred.

**Comment by BruceMillz** [comment]
Despite how nxtruong feels, this behaviour makes very little sense at all. The solver should return the information, not throw an exception. And the information returned in the exception is not very good.
