### ISSUE TITLE
Debug worhp interface

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2161]
Debian travis tests run fine with worhp;
when downloading, doesn't work on my machine.

**Comment by haudren** [comment]
I comment on this because I have been trying to use worhp. Each time I try to solve a problem via the casadi interface, the solve instantly stops with `Final values after iteration 1177108057`. It is as if an integer was badly initialized or something.

I will try to investigate on my own, but if you have any pointers pertaining to this issue, they are more than welcome !

**Comment by jgillis** [comment]
Yup, that's the issue I've seen.

**Comment by haudren** [comment]
The issue disappeared after I compiled Casadi from source on my machine... I am guessing that `worhp.h` changed between `1.10` and `1.12`, which leads to mismatches in the structures' sizes.

**Comment by jgillis** [comment]
Root cause: two different gfortran runtimes being linked into `libcasadi_nlpsol_worhp.so`

**Comment by jgillis** [comment]
Re-open if needed; seems to work now
