### ISSUE TITLE
Changing the Jacobian signature (again)

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#2178]
The (full) Jacobian signature of `F:(x,y)->(r,s) is now:`
```
dF:(x,y,r,s) -> (d([r;s])/d([x;y]))
```
i.e. one big matrix as return.

It would be more user friendly, and potentially more efficient, to split up the output into blocks:
```
dF:(x,y,r,s) -> (dr/dx, ds/dx, dr/dy, dr/dy)
```

If inputs or outputs are nondifferentiable, the corresponding block would be all-zero sparse, cf. #2013

**Comment by Scoeerg** [comment]
Hi @jaeandersson ,

it appears I would like to use this feature, but it remains a mystery how to do it. My minimal example would be

```
#include "casadi/casadi.hpp"

int main() {
// implement a function F:(x,y)->(z)
casadi::MX x = MX::sym("x",2,1);
casadi::MX y = MX::sym("y",1,1);
casadi::MX z = MX::sym("z",2,1);
casadi::Function myFunction = Function("fun", {x, y}, {{x(0) + x(1) + y}, {x(0) * x(1)}}, {"x", "y"}, {"z1", "z2"});
std::vector<double> xValues = {2.0, 3.0};
std::vector<double> yValues = {1.0};
DMDict res = myFunction(DMDict{{"x", xValues}, {"y", yValues}});
Function symbolicJacobiann = myFunction.jacobian();
DMDict numericJacobian = symbolicJacobian(DMDict{{"x", xValues},{"y", yValues}});
return 0;
}
```

Now ideally, I'd split the Jacobian into two parts: `dF/dx` and `dF/dy` symbolically on the function call, somewhat like this

```
// Jacobian w.r.t. x
Function symbolicJacobian_wrt_x = myFunction.jacobian("x");
// Jacobian w.r.t. y
Function symbolicJacobian_wrt_y = myFunction.jacobian("y");
```

rather than splitting the Jacobian after generating `[dF/dx, dF/dy]` into two. But I wished I knew how to do this as well :)
