### ISSUE TITLE
Make CasADi matrices iterable without assertion error in Python

### ISSUE THREAD

**Issue by mahaarbo** [casadi/casadi#2278]
If I write
```python
import casadi as cs
x = cs.MX.sym("x",3)
for i in x:
    print x
```
it produces
```python
x[0]
x[1]
x[2]
```
and then RuntimeError.

I think this amounts to adding a `raise IndexError` in `__getitem__` in [casadi.i](https://github.com/casadi/casadi/blob/54bde1c242fbb229e05fe87310dce3371b1a4af9/swig/casadi.i#L2484) if `s` is larger than `self.size1()*self.size2()`?

**Comment by jgillis** [comment]
Thanks for raising this issue. CasADi matrices have since 3.0 been non-iterable by design.
I added an explicit error to warn the users about this, as well as a fix for your observed error in the case of `iter(x.nz)`

**Comment by mahaarbo** [comment]
May I ask why they were made non-iterable?
As a user, I would have expected numpy-like iteration being possible.

**Comment by jaeandersson** [comment]
>> May I ask why they were made non-iterable?
>> As a user, I would have expected numpy-like iteration being possible.

If you were to iterate over CasADi matrices just like over numpy matrices, you would get horribly inefficient code. Also, CasADi matrices are all sparse, so if it were to be implemented, you'd want to have a behavior similar to `scipy.sparse.csc_matrix`, not `numpy.matrix`:
```python
from scipy.sparse import csc_matrix
A = csc_matrix([[1.,2.],[3.,4.]])
for i in A: print(i)
```
For `casadi.DM` and `casadi.SX`, that might make sense. For `casadi.MX`, this doesn't make sense either, since there are no nonzero entries that can be iterated over - it's a matrix-valued expression.

So rather than implementing something that would almost certainly be bad coding, we choose not to implement anything.
