### ISSUE TITLE
Determinant in numerical evaluation of a Function Object

### ISSUE THREAD

**Issue by KRaetze** [casadi/casadi#2286]
If the casadi determinant function is used in a function object, the dimension of the input is changed from a square matrix to a vector in the case of a numerical evaluation. This behavior can be shown in the following MWE:
```python
import casadi as cas

x = cas.MX.sym('x', 2, 2)
RHS = cas.Function('RHS', [x], [cas.det(x)])

# Working
RHS(x).shape

# Not working
x0 = cas.DM([[1, 3], [5, 6]])
RHS(x0).shape
```

**Comment by jaeandersson** [comment]
I cannot reproduce this. In the latest version of CasADi at least, this script throws the following error for me:
```python
RuntimeError: .../casadi/core/mx_node.cpp:304: 'eval' not defined for class N6casadi11DeterminantE
```
This is expected since `casadi::Determinant::eval` currently isn't implemented. With the recently added support for sparse QR factorization in the core, `casadi::Determinant::eval` could pretty easily be implemented, but this is a separate issue.
