### ISSUE TITLE
"While" and "If" loop like conditional statements are working in the symbolic computation

### ISSUE THREAD

**Issue by KarmvirSinghPhogat** [casadi/casadi#2290]
Dear Andersson,

I am Karmvir Singh from India. I use CasAdi for solving optimal control problems. I have the following queries:

Q 1. How can we incorporate the system dynamics which has a "while" loop or conditional statement "If" loop for solving optimal control problems? 
Example: Nonlinear dynamics which switches under a certain condition. 

Q 2. Can we solve the constrained boundary value problems using CasAdi?
Example: Necessary optimality conditions obtained for an optimal control problem using Pontryagin's maximum principle.

Thank you in advance.

Regards,
- Karmvir.

**Comment by jgillis** [comment]
Boundary value problems can be posed in CasADi by combining an integrator and a rootfinder or NLP solver.

We often deal with systems that are described by ODEs with a smooth right-hand side.
While we have support for `if-then-else` and `while` could be emulated, you may easily end up with a formulation that gives numerical problems (integration method may not work, or NLP solver may fail when using direct transcription).

Your wording seems to suggest you have a mixed-logical dynamical system (like in HYSDEL http://people.ee.ethz.ch/~cohysys/hysdel/, but nonlinear)?
These may give rise to nonvonvex mixed-integer problems when using a direct transcription. Those are fundamentally hard to solve (we have solvers but they scale very bad with horizon length)..

I would first look if your problem is appropriate for dynamic programming, and if not, if it is a fit for the HYSDEL/MPT ecosystem.
CasADi may be a misfit (currently).
