### ISSUE TITLE
Error under SWIG 4.0.1

### ISSUE THREAD

**Issue by metab0t** [casadi/casadi#2522]
Recently, I build `casadi 3.5.1` from source in my Archlinux box with `SWIG`(version 4.0.1) and `Python` (version 3.8) and discovered a bug, which blocks me from importing casadi under Python.
The error message is as follows:
```
Traceback (most recent call last):
  File "ad.py", line 24, in <module>
    from casadi import *
  File "/usr/lib/python3.8/site-packages/casadi/__init__.py", line 32, in <module>
    from casadi.casadi import *
  File "/usr/lib/python3.8/site-packages/casadi/casadi.py", line 71, in <module>
    class _copyableObject(_object):
NameError: name '_object' is not defined
```
However, if I install `casadi 3.5.1` with pip and everything is fine.

The bug seems that it is caused by `casadi.py` generated by SWIG and I compared two files generated by SWIG 4.0.1 (broken) and SWIG 3.0.11(fine). The former lacks definition of `_object`. The two files are uploaded as attach files.

Would you love to give some hints or fixes on this problem?

[casadi-swig4and3.zip](https://github.com/casadi/casadi/files/3879292/casadi-swig4and3.zip)

**Comment by metab0t** [comment]
It seems that `casadi.py` under SWIG 4 and 3 has a large amount of differences.
At present, I install swig3 and create symlink to solve this problem.

**Comment by tmmsartor** [comment]
I'm also using `archlinux`, `CasADi` and Python 3.8 (which is now the default in archlinux),
What do you mean by you installed with `pip`? Did you use a explicit link to a casadi wheel?
Or did you installed a locally build package?
Because as fair as I know `CasADi` `PyPI` package does not support Python 3.8 yet.

### swig 4 changes
Anyway I looked into the `swig` 4.0.X problem.
One of the most relevant changes compare to swig 3.0.X is the drop of the support for 
older python version. [Change log summary](http://swig.org/) says:
`Minimum Python version required is now 2.7, 3.2-3.7 are the only other versions supported.`

### Classic python classes
This means  drop compatibility code to support "classic" (as `swig` call them) python classes for python version older than 2.2 (that's old), different from "modern" python classes.
See python classic classes section in [swig 3.0.X docs](http://swig.org/Doc3.0/Python.html#Python_nn31) .
This is not present anymore in `swig` 4 [docs](www.swig.org/Doc4.0/Python.html), [code](https://github.com/swig/swig/blob/cb5d7398b562e77436e5766fb17a40bfe8c4f973/Source/Modules/python.cxx#L415)

### `_object`
Regarding the the `_object` error you mentioned, my guess is the `_object` is a wrapper to `object` introduced by `swig` to allow the compatibility for this classic classes see swig code [here](https://github.com/swig/swig/blob/fbeb566014a1d320df972aef965daf042db7db36/Source/Modules/python.cxx#L965) and the following  `_newclass` switches, which are not present any more in `swig` 4.0.X `python.cxx` code.

Then my workaround was to replace `_object` with `object` from line 71 of the templated `casadi.py`

A better solution would be fixing the respective line on [`casadi.i`](https://github.com/casadi/casadi/blob/6f122ca22e2a869903628c5738f154c8ac0f7455/swig/casadi.i#L231
) template in order to work also with `swig` 4.0.X out of the box. 

### Python 3.8
I run the test with python3.8 and there are more error than 3.7, but I don't think they are related to this workaround.

@jgillis Are you interested in supporting swig 4 and/or python 3.8, if yes I can make more test and/or look into the other issues.

**Comment by metab0t** [comment]
To be exact, I use pip installed casadi on Python 3.7 on my Windows box.
On the Archlinux box, I use symlinked swig3 to build casadi against Python 3.8. I run some tests and they seem fine.

**Comment by thorade** [comment]
The SWIG py version discussion happened here, in case someone is interested:
https://github.com/swig/swig/issues/701
