### ISSUE TITLE
Operator[] is missing

### ISSUE THREAD

**Issue by Mo-Riad** [casadi/casadi#2673]
I am currently working on a project that is based on casadi and I uses casadi::MX. I am currently facing a problem when writing a template methods that works with vector<Type> and Casadi as usually element accessing is done using operator[] however in Casadi::MX it is done using operator(). It would be really great if a similar operator exists which would save me writing the same code twice just to replace () with [].

**Comment by Mo-Riad** [comment]
Something like 

`MX operator[](size_t idx) const
    {
      return (*this)(idx);
    }`

**Comment by jaeandersson** [comment]
CasADi C++ syntax is not written to be a drop-in replacement of array types. And using it as such is almost never a good idea. A solution of what you're trying to do is to use function overloading:
```c++
double get_elem(const std::vector<double>& v , size_t i) { return v.at(i);}
MX get_elem(const casadi::MX& v, size_t i) {return v(i);}
```
You could also use C++ traits.

Another idea is to use casadi::DM instead of your vector type. casadi::DM and casadi::MX have the same syntax.
