### ISSUE TITLE
Issues using linear solvers with IPOPT

### ISSUE THREAD

**Issue by stonkens** [casadi/casadi#2769]
I have attempted to install the HSL solvers following [Obtaining HSL](https://github.com/casadi/casadi/wiki/Obtaining-HSL) instructions. I have attempted this on Ubuntu 20.04 and Ubuntu 20.04 through WSL. 

I get the following error: 
```
Exception of type: OPTION_INVALID in file "../../../../Ipopt/src/Algorithm/IpAlgBuilder.cpp" at line 321:
 Exception message: Selected linear solver MA27 not available.
Tried to obtain MA27 from shared library "libhsl.so", but the following error occured:
/lib/libhsl.so: undefined symbol: metis_nodend_
```

I installed casadi with `pip install casadi` (which also installs `ipopt` directly). Addtionally I added `metis` package as indicated in [Obtaining HSL](https://github.com/casadi/casadi/wiki/Obtaining-HSL). How can I circumvent this issue?

**Comment by juandavid212** [comment]
Hello, did you manage to solve this?
I'm trying to use it on Matlab.

**Comment by 0aax** [comment]
Had the same issue after following the "Obtaining HSL" instructions with CasADI installed via pip on Fedora 30. What I ended up doing was compiling the HSL code using [ThirdParty-HSL](https://github.com/coin-or-tools/ThirdParty-HSL), which is one of the options that Ipopt gives in its [documentation](https://coin-or.github.io/Ipopt/INSTALL.html). The shared library `libcoinshsl.so` gets created in `/usr/local/lib`, but since Ipopt looks for `libhsl.so` make a symbolic link from `libcoinhsl.so` to `libhsl.so`.
```
ln -s /usr/local/lib/libcoinhsl.so /usr/local/lib/libhsl.so
```
Then make sure Ipopt knows where to look.
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
```

**Comment by haavardok** [comment]
I got the same error as @stonkens got after following the installation instructions of [Obtaining HSL](https://github.com/casadi/casadi/wiki/Obtaining-HSL).

The solution for me was similar to @0aax's although I went in a slightly different direction after utilizing the [ThirdParty-HSL](https://github.com/coin-or-tools/ThirdParty-HSL) code. Instead of making a symbolic link I set the IPOPT option `hsllib` in my Python code to `"hsllib": "/usr/local/lib/libcoinhsl.so"`.
