### ISSUE TITLE
Name method of SX.sym throws error if symbol is not scalar

### ISSUE THREAD

**Issue by 4flixt** [casadi/casadi#2781]
Best explained with a short example. This works as expected:
```python
SX.sym('name').name()

>> name
```
On the other hand:
```python
SX.sym('name', 2,1).name()

>> RuntimeError: .../casadi/core/matrix_impl.hpp:1178: Assertion "is_scalar()" failed:
Can only convert 1-by-1 matrices to scalars
```

For ``MX`` I get the expected behavior:
```python
MX.sym('name', 2,1).name()
>> name
```

**Comment by jgillis** [comment]
Hi there,

This is expected behaviour in fact.
An SX object can be interpreted as a container with scalar symbolic entities. These entities can have a name, but a name of the container is ill defined.
In the case of MX, there is container. The MX is directly a symbolic entity with potentially nonscalar shape

**Comment by 4flixt** [comment]
Thank you @jgillis, I see now that
```python
SX.sym('name', 2,1)[0].name()
```
does return:
```
'name_0`
```
Makes sense 👍
