### ISSUE TITLE
Interface to MILP/QP solver HiGHS

### ISSUE THREAD

**Issue by felixlen** [casadi/casadi#2851]
[HiGHS](https://github.com/ergocode/highs) is a recent MILP and QP solver development with permissive MIT License. For several of my use cases it outperforms CBC and thus would like to see it in CasADi.

I have created an interface to HiGHS, based on the CBC interface in CasADi which is working for my testcases with one drawback: Solver output is still sent to stdout as HiGHS does not seem to support to redirect output to a stream, only to log files.

If it is of interest to include it into CasADi, I am happy to share it and open a pull request.

**Comment by jaeandersson** [comment]
Nice! Since it's an active set method, I assume that you get the exact active set? That could be useful for sensitivity analysis. Sure, feel free to make a pull request. Since the source code is on Github, maybe it can be included as a git submodule in "external_packages"? I saw that there is a Math. Prog. Comp. paper, will take some time to read it.

**Comment by felixlen** [comment]
Thanks a lot for the comments and sorry for the delay, was quite busy in between. I have created a pull request and suggest to continue the discussion there.
