### ISSUE TITLE
DaeBuilder.parse_fmi error

### ISSUE THREAD

**Issue by koenstrien** [casadi/casadi#3084]
Hi All,

I have been trying to import an fmu file using the DaeBuilder.parse_fmi(). I hoped that this should work for casadi 3.6.0. Maybe I am doing something wrong but I cannot find documentation or examples on this topic (yet). For now, I have build FMI 3.0 .fmu files based on https://github.com/modelica/Reference-FMUs to use as an example (BouncingBall.fmu)
I try to run:
```
from casadi import DaeBuilder

ocp = DaeBuilder()
ocp.parse_fmi("./fmus3/BouncingBall.fmu")

```
I get the error:
```
Traceback (most recent call last):
  File "path/to/test.py", line 4, in <module>
    ocp.parse_fmi("./fmus3/BouncingBall.fmu")
  File "path/to/python3.10/site-packages/casadi/casadi.py", line 43795, in parse_fmi
    return _casadi.DaeBuilder_parse_fmi(self, *args)
RuntimeError: .../casadi/core/shared_object.cpp:95: Assertion "!is_null()" failed:
Notify the CasADi developers.
```

I was wondering whether this is a problem, or I am doing something wrong. Additionally I was wondering whether the workflow should also work for FMU 2.0, or only for FMU 3.0. Thank you in advance!

**Comment by jaeandersson** [comment]
Hello, some clarifications:
 * Currently there is a first version of FMU import that supports FMI 2.0 (only) and there is a working prototype for FMU export that outputs FMU 3.0 (only). I plan to develop especially the FMI import support further in the near future, especially concerning documentation and probably some bugfixes. I think the longer term development plans will depend on the needs by industrial partners. The same is also true for FMU export: we now know how we can do FMU export efficiently, and the approach relies on a mature and efficient part of CasADi (C code generation), but for getting the support really mature, it needs to be used in different applications.
 * The `DaeBuilder.parse_fmi()` refers to a symbolic FMI export - that is with CasADi expressions constructed from the model equations. It uses a format based on FMI 1.0 and was used for in first version of the coupling between JModelica.org and CasADi. It is also supported, at least to some extent, by OpenModelica. After JModelica.org moved on to a different way of coupling to CasADi, this feature has been pretty stagnant. We keep it for now, and if you can get it to work for a particular application, it will probably be very efficient (since it's a symbolic format). But it's not really mature, and probably never will be. The argument of the call by the way should be an .xml file, not an .fmu file.
* The syntax for the new FMI import can be seen in the following example: https://github.com/casadi/casadi/blob/master/docs/examples/python/modelica_fmu_import.py. There will probably be more and better documentation in the coming months.
* The bouncing ball example may not be the best example since the new interface does *not* support hybrid dynamics. Supporting hybrid dynamics is definitely something we could do, including in the ODE/DAE sensitivity analysis, but it probably won't happen until there is a good use case.

**Comment by jaeandersson** [comment]
Great that you could import the model. There will be continued work on the FMI import support in the next few months, especially to ensure that it works well for ODE/DAE sensitivity analysis. C code export support would be a major effort, probably 2 or 3 weeks of my time, so I won't go there until there is a project that can justify it.

**Comment by koenstrien** [comment]
Allright. For me the use case would be to use a (non-linear) model designed in OpenModelica and use it to design a model-predictive controller using acados + casadi. Right now I import the FMU and linearize it around the current state to find the best local control, and reiterate every step. If I could somehow pass the whole (non-linearized) system of equations of the FMU to the casadi model I can potentially calculate the whole optimal control path in one go.

**Comment by jaeandersson** [comment]
> Allright. For me the use case would be to use a (non-linear) model designed in OpenModelica and use it to design a model-predictive controller using acados + casadi. Right now I import the FMU and linearize it around the current state to find the best local control, and reiterate every step. If I could somehow pass the whole (non-linearized) system of equations of the FMU to the casadi model I can potentially calculate the whole optimal control path in one go.

Nice. Yes, the export could definitely be useful there.
