### ISSUE TITLE
How to obtain the dual multipliers with Gurobi and Casadi?

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#3109]
### Discussed in https://github.com/casadi/casadi/discussions/3106

<div type='discussions-op-text'>

<sup>Originally posted by **lalajiayou** April 14, 2023</sup>
Hi, everyone, I encountered the following problem:
For the same SOCP optimization problem that is with feasible solutions, gurobi can solve it, but cannot return the dual multiplier normally (NaN); On the contrary, Ipopt can both solve normally and return dual variables. So, my question is how to obtain the dual multipliers with Gurobi and Casadi?

The corresponding codes are as follows:

opti = casadi.Opti();
opti.solver('ipopt')
%opti = casadi.Opti('conic');
%opti.solver('gurobi')
[~,sol] = evalc('opti.solve();');
lambda = sol.value(opti.lam_g)

I have noticed the following discussion, but there are still some doubts. I am not sure which file to modify. If anyone could reply, I would greatly appreciate it!
https://groups.google.com/g/casadi-users/c/IWRTF1IcU3s/m/k45pn8leAAAJ</div>

**Comment by shn66** [comment]
I think this issue is still lingering... Posting an example below:

========== code ============
import casadi as ca
op=ca.Opti("conic")
op.solver("gurobi",{'error_on_fail':0},{"QCPDual":1})
v=op.variable(4)
soc=ca.soc(v[-3:-1], -0.5+v[-1])
op.subject_to(soc>0)
op.subject_to(op.bounded(-1,v,1))
op.minimize(v.T@v)
sol=op.solve()
print(sol.value(v),  sol.value(op.lam_g))

~~~~~~~~~~output~~~~~~~~~~~~~

[-0.  -0.  -0.   0.5] [nan nan nan nan]
