### ISSUE TITLE
Error when running ca.nlpsol with ipopt in casadi 3.6.2

### ISSUE THREAD

**Issue by SGeevers** [casadi/casadi#3164]
When using casadi 3.6.2 with Python 3.9.0 and running something like

```python
import casadi as ca
...
ca.nlpsol('nlp', 'ipopt', nlp, nlpsol_options)
```

I get an error message of the form

> Failed with Error: .../casadi/core/function_internal.cpp:145: Error calling IpoptInterface::init for 'nlp':
> Error in Function::factory for 'nlp' [MXFunction] at .../casadi/core/function.cpp:1758:
> Failed to create nlp_grad:[x, p, lam:f, lam:g]->[f, g, grad:gamma:x, grad:gamma:p] with {"gamma": [f, g]}:
> .../casadi/core/factory.hpp:584: Gradient generation failed:
> Error in MX::gradient at .../casadi/core/generic_matrix.hpp:1466:
> Error in MX::jtimes at .../casadi/core/generic_matrix.hpp:1454:
> Error in MX::reverse at .../casadi/core/mx.cpp:1788:
> Error in MXFunction::ad_reverse at .../casadi/core/mx_function.cpp:1101:
> Error in MX::ad_reverse for node of type N6casadi12SparsityCastE at .../casadi/core/mx.cpp:2310:
> .../casadi/core/sparsity_cast.cpp:86: Assertion "aseed[d][0].sparsity().is_subset(sparsity())" failed:
> Notify the CasADi developers.

**Comment by jgillis** [comment]
Could you share, possibly in a secret gist, the offending code?

**Comment by eaglema** [comment]
> Could you share, possibly in a secret gist, the offending code?
Hi Gillis,

I encountered the same problem as Geevers. This happens when I'm using ‘u’ from the ODE integrator as decision variables for the NLP problem to be created. Note that the error only happens when there are multiple time points defined for ODE integrator, e.g., tf is a list or array, and it works fine when tf is a scalar. Please check the following demo code:

# Error reported when using u and multiple time points (ODE)
import casadi as cas

# Define ODE problem
x = cas.MX.sym('x')
u = cas.MX.sym('u')

x_dot = -x + u

ode_prob = {'x': x, 'u': u, 'ode': x_dot}
ode_fun = cas.integrator('dae_fun', 'cvodes', ode_prob, 0, [1, 2])
sol = ode_fun(x0=1., z0=1., u=u)
xf = sol['xf']

# Define NLP problem
f = cas.sumsqr(xf)
nlp_prob = {'x': u, 'f': f}
nlp_fun = cas.nlpsol('nlp_fun', 'ipopt', nlp_prob)
print(nlp_fun)

Hope the issue can be resolved very soon. Thank you very much! 
Best wishes,
Yingjie

**Comment by jgillis** [comment]
Reduced to
```
x = MX.sym("x",3)

xy = vertcat(0.8,0.2)
w = MX(sparsify(DM([1,1,0])).sparsity().T,xy) @ x

f = Function('f',[x],[w])
f.reverse(1)
```

**Comment by jgillis** [comment]
@eaglema I moved your question to #3186; it's a different bug alltogether
