### ISSUE TITLE
`casadi.nlpsol`: linear vs. non-linear constraints

### ISSUE THREAD

**Issue by gregreich** [casadi/casadi#3400]
Hi

Is there a way to have non-linear solvers distinguish linear from non-linear constraints when accessed through the `casadi.nlpsol` interface?

I'm using KNITRO and MATLAB, but the option `detect_linear_constraints` is rejected as unknown.

Thanks and best, Gregor.

**Comment by tinusd** [comment]
Hi Gregor

You are likely not setting the option correct. It should be "options.detect_linear_constraints = true", where you then pass "options" to "nlpsol". However, this will not make a difference, since Knitro's API changed with their recent releases; see https://github.com/casadi/casadi/discussions/3260.

**Comment by gregreich** [comment]
Thanks for the reply, tinusd! Indeed, I set it as part of the solver-specific options, and thus "one level too deep". But as you said, it has no effect for recent versions of KNITRO.
