### ISSUE TITLE
2.4 to 3.0 migration documentation is incomplete

### ISSUE THREAD

**Issue by nog642** [casadi/casadi#3453]
I was trying to get some old code to run and ran into #2226 (the `daeIn` and `daeOut` functions were removed in 3.0.0).

I looked into https://github.com/casadi/casadi/wiki/Changes-v2.4.0-to-v3.0.0 but found no information about how to migrate the code to version 3.0. I think this page should defeinitely be updated to explain how to migrate `daeIn` and `daeOut`.

I have never used this library before and have very little idea where to start.

**Comment by jaeandersson** [comment]
CasADi 3.0 was a major non-backwards compatible change in syntax. To update from 2.4 to 3.0 you need to be familiar with both the old syntax and the new syntax. If you never used CasADi before, you might want to ask someone for help. daeIn/daeOut were just helper functions that returned lists with with entries in a particular order.

**Comment by jaeandersson** [comment]
See this comment: https://github.com/casadi/casadi/issues/2226#issuecomment-377947626
CasADi 3.0 does not have IO schemes of older versions of CasADi.

**Comment by nog642** [comment]
I don't know anyone who is familiar with the library.

The [example](https://github.com/casadi/casadi/blob/main/docs/examples/python/dae_single_shooting.py#L67-L69) linked in that comment does not use `Function`, but https://github.com/casadi/casadi/wiki/Changes-v2.4.0-to-v3.0.0 says:

> `SXFunction`: Call the constructor of the `Function` class instead. In practice this means renaming `SXFunction` -> `Function`

I get that 3.0 was a major syntax change, but isn't the purpose of the https://github.com/casadi/casadi/wiki/Changes-v2.4.0-to-v3.0.0 page to detail those changes? Having better documentation for migrating to newer versions is much better than telling users to get familiar with the old syntax (presumably by looking at the old documentation, which you have to dig for). Why not explain the changes to the IO schemes on that page? Because currently it's not there.

**Comment by jaeandersson** [comment]
There is no need for io schemes in CasADi 3. Before, it was used as helper functions in constructors such as Integrator. CasADi 3 simplified the syntax by only having a single Function class in the public API. In the helper functions (e.g. integrator) that replaced the constructors (e.g. Integrator), you typically pass dictionaries of expressions to specify the problems, instead of functions created by Io schemes. Io schemes where also used in function calls. With the generalized calling syntax, you don't need it anymore. These two changes (calling syntax and Function syntax) are already in the migration documentation as far as I can tell. Exactly when daeIn etc was deprecated I don't remember. Usually nothing is removed from one release to another. If it was removed in CasADi
