### ISSUE TITLE
How to use float for casadi::DM

### ISSUE THREAD

**Issue by AndrePatri** [casadi/casadi#3796]
Hi, 
I have an application which uses Casadi's code generation feature. I was thinking of using floating point representation for data, to check whether I can get some kind of performance boost compared to using double precision data. I saw from the documentation/code that it's possible to codegenerate c functions which use float dtype by setting a "casadi_real" flag in the generation options.
So I tried to adapt my already existing cpp code to allow switching between float and double to allow interfacing with float-based codegenerated functions, but I am stuck at this compilation error 

`error: no match for call to '(casadi::Function) (const float**, float**, long long int*, float*, casadi_int&)' 
`
Thrown by this line of code
`_f(_in_buf.data(), _out_buf.data(), _iw.data(), _dw.data(), mem);`, where `_f` is a  `casadi::Function `.

 `_in_buf ` is a  `std::vector<const Real *> ` where  ` Real` is defined based on a preprocessor directive to either float or double. I think the compilation error only occurs when it's float due to `std::vector<DM> operator()(const std::vector<DM>& arg) const;` in `casadi::Function` using `casadi::DM` being defined as `casadi::Matrix<double>`.
Is there I workaround I can use to allow casadi::Function to use float instead of double representation? 
Thanks in advance for any help

**Comment by jgillis** [comment]
There are basically two modes of evaluating CasADi Functions:
 * Use the virtual machine. This happens when you use `operator()`
 * Generate code and use that code without any further involvement of CasADi

Only the latter allows single precision evaluation. The fact that you have `casadi::Function` in your compiler error suggests that you are doing the former route, which is indeed incompatible with floats.
