### ISSUE TITLE
Cannot hash for vectors

### ISSUE THREAD

**Issue by HaizhouZ** [casadi/casadi#3846]
Call to
```
import casadi as cs
dyn.q = cs.SX.sym('q', 3)
print(hash(dyn.q))
```
Results:
```
Traceback (most recent call last):
  File "/home/harper/Documents/contact_tamp/traj_opt_acados/test_optim.py", line 120, in <module>
    print(hash(dyn.q))
          ^^^^^^^^^^^
  File "/home/harper/miniconda3/lib/python3.11/site-packages/casadi/casadi.py", line 9016, in __hash__
    return SharedObject.__hash__(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harper/miniconda3/lib/python3.11/site-packages/casadi/casadi.py", line 831, in __hash__
    return _casadi.SharedObject___hash__(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: Wrong number or type of arguments for function 'SharedObject___hash__'.
  Prototype:
__hash__(self)
  You have: 
```

**Comment by JamesParrott** [comment]
I've reproduced this.  The Python code causing the error was generated by SWIG.  This needs somebody who understands Casadi's Swig Python interface file.

**Comment by HaizhouZ** [comment]
> Can you please describe the intent?

 I want to use a dict[cs.sx, ...]. Also the .name method does not work for vectors. It would be convenient to have any of them. For now I just hacked it by adding an attribute to the SX object.

**Comment by jgillis** [comment]
SX is in fact a container type that contains sparse scalar entries of type SXElem (a type that is not exposed to the user).
It is a mutable container: you can do `A=ca.SX.sym('x',2);A[0] = 1`

There is a fundamental difficulty with assigning a hash to a mutable container.
In pure python:
```
In [1]: a=[1,2,3]

In [2]: hash(a)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-57b555d30865> in <module>
----> 1 hash(a)

TypeError: unhashable type: 'list'
```

I notice that I tried to 'fix' the hash routine 7years ago with a fallback to SharedObject, but that's a mistake since SX is not a SharedObject, hence the swig error.

Name is also a problem. Each entry in the container will have a different name. How would you define the overall name?

**Comment by jgillis** [comment]
Please reopen if you can write a proposal of how a hash would be defined for a non-scalar SX
